### ISSUE TITLE
Error causing server to crash.

### ISSUE THREAD

**Issue by SugarRealms** [iSach/UltraCosmetics#17]
Here is the error: http://pastebin.com/cqPu8hMU

**Comment by iSach** [comment]
Is this fixed in 2.0.3?

**Comment by xion87** [comment]
not fixed got the same error spam:
http://hastebin.com/qatopamowi.avrasm
plus the followings errors (i am at offline mode)
- http://hastebin.com/ogececumaj.vbs

**Comment by Someone-NEW** [comment]
Not fixed used latest version. And Hastebin cleared every 5 hours so than is not possible see what you paste here
Use pastebin or justpasteit

**Comment by iSach** [comment]
Caused by Minecraft pathfinders.
