### ISSUE TITLE
Pets can be killed when changing world

### ISSUE THREAD

**Issue by Elric02** [iSach/UltraCosmetics#435]
### What steps will reproduce the issue?  
1. spawn a pet
2. change world (using Multiverse)
3. go back to the world where you spawned the pet

### What happened? 
You can now kill your pet when doing this!

### What version of UltraCosmetics are you using?  
2.4.9

### What Spigot version are you using? Paste the output of /version below.  
CraftBukkit version git-Spigot-da42974-8f47214 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

### What plugins do you have installed? Paste the output of /plugins below.  
PlaceholderAPI, NametagEdit, EntityDetection, WooMinecraft, ViaVersion, BuycraftX, Multiverse-Core, LibsDisguises, PermissionsEx, MyCommand, Essentials, UltraCosmetics

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
none

**Comment by iSach** [comment]
Should be fixed in 2.5
Please re-open if it's not. Sorry for the inconvenience and delay.

**Comment by Elric02** [comment]
Hi,
Sorry for the late answer
Still doesn't work, when I change world (using v2.5.5) the pet keeps there and if I come back I can hurt him and kill him like a normal mob
